"""initial schema

Revision ID: 086673a46198
Revises: 
Create Date: 2026-04-14 12:23:31.741716

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '086673a46198'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('handoff_targets', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_roles_name'), ['name'], unique=True)

    op.create_table('swarm_compositions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('roles', sa.Text(), nullable=False),
    sa.Column('max_rounds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('swarm_compositions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_swarm_compositions_task_type'), ['task_type'], unique=True)

    op.create_table('swarm_instances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=False),
    sa.Column('task_name', sa.String(length=256), nullable=False),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('branch', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('active_agent', sa.String(length=64), nullable=True),
    sa.Column('conversation_log', sa.Text(), nullable=True),
    sa.Column('pr_url', sa.String(length=512), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('swarm_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_swarm_instances_completed_at'), ['completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_swarm_instances_status'), ['status'], unique=False)
        batch_op.create_index('ix_swarm_instances_status_completed', ['status', 'completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_swarm_instances_task_id'), ['task_id'], unique=True)

    op.create_table('system_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('system_settings')
    with op.batch_alter_table('swarm_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_swarm_instances_task_id'))
        batch_op.drop_index('ix_swarm_instances_status_completed')
        batch_op.drop_index(batch_op.f('ix_swarm_instances_status'))
        batch_op.drop_index(batch_op.f('ix_swarm_instances_completed_at'))

    op.drop_table('swarm_instances')
    with op.batch_alter_table('swarm_compositions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_swarm_compositions_task_type'))

    op.drop_table('swarm_compositions')
    with op.batch_alter_table('agent_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_roles_name'))

    op.drop_table('agent_roles')
    # ### end Alembic commands ###
