"""PR delivery pipeline (FR-6).

Runs after the swarm finishes. On success: commit + push + open PR +
update task status to 'done' + comment with PR URL. On failure: revert
task status to 'error' and post a failure comment.
"""
from __future__ import annotations

import logging

from syntexa.adapters.base import ProjectManagementAdapter, RepositoryAdapter
from syntexa.adapters.clickup import AdapterError
from syntexa.daemon.swarm import SwarmContext, SwarmResult

logger = logging.getLogger(__name__)


class DeliveryPipeline:
    def __init__(
        self,
        repo: RepositoryAdapter,
        pm: ProjectManagementAdapter,
    ) -> None:
        self._repo = repo
        self._pm = pm

    def deliver(self, ctx: SwarmContext, result: SwarmResult) -> str | None:
        """Return the PR URL on success, None otherwise."""
        if result.status != "completed":
            self._report_failure(ctx, result)
            return None

        try:
            commit_message = result.pr_title or f"chore({ctx.task_type}): {ctx.task_name}"
            self._repo.commit(ctx.branch, commit_message, result.modified_files)
            self._repo.push(ctx.branch)
            pr = self._repo.create_pr(
                head=ctx.branch,
                base=ctx.base_branch,
                title=result.pr_title or commit_message,
                body=_format_pr_body(ctx, result),
            )
        except AdapterError as exc:
            logger.exception("Delivery failed for task %s", ctx.task_id)
            self._report_failure(
                ctx,
                SwarmResult(
                    status="failed",
                    conversation_log=result.conversation_log,
                    error=str(exc),
                ),
            )
            return None

        self._report_success(ctx, pr.url)
        return pr.url

    def _report_success(self, ctx: SwarmContext, pr_url: str) -> None:
        try:
            self._pm.update_status(ctx.task_id, "done")
            self._pm.add_comment(
                ctx.task_id,
                f"Syntexa swarm completed. Pull request ready for review: {pr_url}",
            )
        except AdapterError:
            logger.exception("Could not update task %s on success", ctx.task_id)

    def _report_failure(self, ctx: SwarmContext, result: SwarmResult) -> None:
        try:
            self._pm.update_status(ctx.task_id, "error")
            self._pm.add_comment(
                ctx.task_id,
                _format_failure_comment(result),
            )
        except AdapterError:
            logger.exception("Could not update task %s on failure", ctx.task_id)


def _format_pr_body(ctx: SwarmContext, result: SwarmResult) -> str:
    parts = [
        result.pr_body or f"Automated change for task `{ctx.task_id}`: {ctx.task_name}",
        "",
        f"Task type: `{ctx.task_type}`",
        f"Source task: `{ctx.task_id}`",
        "",
        "---",
        "_Generated by Syntexa swarm._",
    ]
    return "\n".join(parts)


def _format_failure_comment(result: SwarmResult) -> str:
    if result.status == "timeout":
        return "Syntexa swarm timed out. Task reverted for manual review."
    err = result.error or "Unknown error"
    return f"Syntexa swarm failed. Task reverted. Reason: {err}"
