"""add external_credentials table

Revision ID: f544d974925d
Revises: 086673a46198
Create Date: 2026-04-22 12:04:27.462439

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f544d974925d'
down_revision: str | Sequence[str] | None = '086673a46198'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_credentials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_type', sa.String(length=32), nullable=False),
    sa.Column('credentials', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('external_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_credentials_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_credentials_service_type'), ['service_type'], unique=False)

    op.drop_table('sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('token', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    with op.batch_alter_table('external_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_credentials_service_type'))
        batch_op.drop_index(batch_op.f('ix_external_credentials_is_active'))

    op.drop_table('external_credentials')
    # ### end Alembic commands ###
